spring.application.name=asistente-academico-virtual

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=asistente_academico;encrypt=false
spring.datasource.username=appuser
spring.datasource.password=Asistente2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8080